# This is a basic workflow to help you get started with Actions

name: Jupyter Notebook 1.initial_assessment.ipynb

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '*/5 * * * *'
  #   - cron: '0 */4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get -y --force-yes install chromium-chromedriver
        npm install -g electron@6.1.4 orca
        pip3 install pandas numpy ipykernel jupyter scipy tqdm statsmodels
        python3 -m ipykernel install --user --name python3
        sudo chmod -R 777 .
    - name: Run Notebook
      uses: yaananth/run-notebook@v1
      with:
        notebook: "notebooks/1.initial_assessment.ipynb"
        isReport: False
        poll: True
